const a : int := 5
const b : int := 3
const c : real := 0.1
const d : real := 0.2
const e : string := "987"
const f : string := "654"
const g := true
const h := false

const i := a > b
const j := b < c
const k := c >= d
const l := d <= a
const m := a <= true
const n := e < f
const o := g > h
const p := h <= a
var q := true
var r := false
const s := q <= a
const t := q >= g
const u := r > q
q := false
a := 10