const a : int := 5*2

const b : int := 4/2

const c : int := 5/4

const d := 0.2*0.5

const e : int := 5*(3+2)

const f : int := 4--2

const g : int := 4-(-2)

const h : real := 4.0/2.0

const i : real := 5.0/4

const j : real := 5/4.0

const k : real := -4

const l : real := 5/true



const n : real := "12356"/5

const p : int := -4

const q : real := -4

const r : int := -4/0

const s : real := -4/0.0

const t : int := -4/0.0

const u : real := -4/0

