const c:= 5

if (c > 10) then
  put -c
  skip
else 
  put c
  skip
end if


if (c > 2) then
  put c+c
  skip
end if


if (c>10) then
  put 1+c
  skip
else 
	if (c>2)then
  	put 2+c
        skip
	else
	put 3+c
	end if
 put 4+c
 skip
end if
 
 
if (c>1) then
  put 10+c
  skip
	if (c>6)then
  		put 20+c
		skip
   	else 
    		put 30+c
		skip
	end if
put "123"
skip
end if

 
if (c>1) then
  put 1+c
  skip
	if (c>2)then
  	put 2+c
        skip
	end if
else 
 put 4+c
 skip
end if
 
 
if (c>1) then
  put 10+c
  skip
	if (c>2)then
  	put 20+c
	skip
	end if
put "123"
skip
end if
